### PR TITLE
Fixed URL

### PR DESCRIPTION
**Pull request by YourMCGeek**
fulllstack.network -> fullstack,network

### CODE REVIEW

**Comment by KensoDev** [comment]
@YourMCGeek Thank you for this!

**Comment by YourMCGeek** [comment]
@KensoDev All good! I know sometimes we type fast and don't look at the little details like an extra "l" :+1:

**Comment by KensoDev** [comment]
Makes me think of a product... Validating links in your Github READMEs

**Comment by YourMCGeek** [comment]
@KensoDev I'd be down to help you of that if you do make it :)

**Pull request merged**
