### PR TITLE
Stations by networks

### PR DESCRIPTION
**Pull request by tylors1**
GET stations given a network_id, in stations.js

### CODE REVIEW

**Comment by KensoDev** [comment]
so, if you want to actually commit into this project, would love to pull this in.
However, you will need to create a directory with your team name.

**Comment by KensoDev** [comment]
Also, you don't usually commit `node_modules` into the project. You have a lock file that you commit in and make sure everyone is on the same version.

**Comment by tylors1** [comment]
Yeah, just noticed all my mistakes with this request. Went to the wrong git I believe. Anyway to remove this?

**Comment by KensoDev** [comment]
You can close this PR and delete the branch. Fix it in another branch and re-push

**Comment by KensoDev** [comment]
I will go ahead and close this PR

**Pull request closed without merging**
